<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>44a6918d-a32d-4d86-8567-6edbc65172b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register_Layer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='register_Layer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd7b7621-fe53-4331-b0b6-df481b3a0153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Jobseeker Register</value>
      <webElementGuid>e152c3df-4286-4992-9b17-26f6be623916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.naukri.com/registration/createAccount?othersrcp=22636</value>
      <webElementGuid>c10907fa-a117-44d7-84e7-ac3c3915a9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register_Layer</value>
      <webElementGuid>7d3417f3-c0d3-47c4-81c5-a2195e4d5ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-track</name>
      <type>Main</type>
      <value>Main Navigation Register|Register Icon</value>
      <webElementGuid>17275959-8bc5-45b1-b094-011df2ebf3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nI-gNb-lg-rg__register</value>
      <webElementGuid>243610eb-be10-4cbe-96e7-52eba1b919ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>734eba19-3779-46e8-8251-21bdd8ea1c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_Layer&quot;)</value>
      <webElementGuid>780948d2-ad61-40bd-888b-212642b6236c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='register_Layer']</value>
      <webElementGuid>c60313cc-5ae1-42bc-bb16-ea2b6152222b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div[2]/div/a[2]</value>
      <webElementGuid>21fc6705-6280-453e-a582-78c6ad0d2786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>f4322310-24ea-42a8-bd64-6a3b57281e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>ecca8f23-d375-4a1f-9c9a-3562de664dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job letter samples'])[1]/following::a[2]</value>
      <webElementGuid>458a301a-443f-448b-a66e-9ef6025c97ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For employers'])[1]/preceding::a[1]</value>
      <webElementGuid>4fd90371-0ab3-4afb-b121-03933b9b6e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post a job'])[1]/preceding::a[2]</value>
      <webElementGuid>db1c1f35-e614-4b7c-a5ce-5b5eaee2ee3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>7313e8df-0b6e-4e7f-9c50-c78e6677ddd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.naukri.com/registration/createAccount?othersrcp=22636')]</value>
      <webElementGuid>148c5762-e76b-4761-b742-ec7ed262b6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>405d075e-9730-406b-9c5b-aea6e4bd5329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Jobseeker Register' and @href = 'https://www.naukri.com/registration/createAccount?othersrcp=22636' and @id = 'register_Layer' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>438e9c8a-37d4-4790-8968-0c19110f9049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
