<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_12</name>
   <tag></tag>
   <elementGuidId>f10653c7-d1b7-4873-86ff-03657b35958a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='46121b16-25f3-4054-8208-7539b8e88f1f_cell_selected']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#46121b16-25f3-4054-8208-7539b8e88f1f_cell_selected > a.k-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fd1b02b-ae46-4bc5-a43d-4a42bbf1d151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>541bc535-027d-44d7-9b1b-f9a90376d738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>a9a153e3-550e-43ed-b92e-be32cbab9ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e2b81c82-57e6-4eb4-86db-b27a9da243b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2023/9/12</value>
      <webElementGuid>a88823cf-6f9c-41ce-8551-239ec8a1e6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thursday, October 12, 2023</value>
      <webElementGuid>4287da1e-7d94-40e1-8acf-f79bf3e937bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>1c196f63-f5ae-47b8-8aae-680276eed1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;46121b16-25f3-4054-8208-7539b8e88f1f_cell_selected&quot;)/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>e7ffce26-a86b-44bc-b906-b5ba7d29f6f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='46121b16-25f3-4054-8208-7539b8e88f1f_cell_selected']/a</value>
      <webElementGuid>9f6881f6-f1ed-427e-813c-d31d23b45df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'12')])[3]</value>
      <webElementGuid>61fa02cd-77e8-4f72-ab18-1a71ae8ba67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::a[12]</value>
      <webElementGuid>06aa7775-5be6-4d45-a3fb-81e0fd23e03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[2]/following::a[12]</value>
      <webElementGuid>8ec5a244-4f9d-4cc9-9d7c-c93b4b9f077b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[12]/preceding::a[32]</value>
      <webElementGuid>5d213f16-16d2-456f-b743-6540c9036ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[7]/preceding::a[32]</value>
      <webElementGuid>11959d27-0dc7-4d42-bafa-64749fc1d751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[82]</value>
      <webElementGuid>2a338f7d-e1ac-4687-85f7-84387ff881e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/table/tbody/tr[2]/td[5]/a</value>
      <webElementGuid>6b8a92e3-bd30-4df5-bac6-f89dc72deec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Thursday, October 12, 2023' and (text() = '12' or . = '12')]</value>
      <webElementGuid>02dc0137-e0d1-41af-b43c-418b24079ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
