<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_0.00_orders-grid_next</name>
   <tag></tag>
   <elementGuidId>b03fefab-61f0-4f2a-ba00-01b7e31e1f28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='orders-grid_next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#orders-grid_next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4b045105-e859-4a2e-b548-213054ddd8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item next disabled</value>
      <webElementGuid>05a26544-ee0c-4f15-a191-b605a4ddad19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>orders-grid_next</value>
      <webElementGuid>6bf7afd8-1571-4eee-b1fe-2dfeb1e7b5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orders-grid_next&quot;)</value>
      <webElementGuid>35bbfd8b-008e-4cea-97d2-7e30eedaefee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='orders-grid_next']</value>
      <webElementGuid>3a6dcbdd-efca-49d0-8593-ee3563aa29cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orders-grid_paginate']/ul/li[2]</value>
      <webElementGuid>3950c6cc-3ff6-49e2-ba47-1b075a43abbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[6]/following::li[2]</value>
      <webElementGuid>84691e0f-9df7-473a-8c66-d8ce1ce9212a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records'])[1]/preceding::li[1]</value>
      <webElementGuid>e1865e66-8cb8-4b28-b52f-cf0ebe9b80f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[2]</value>
      <webElementGuid>df8805ec-608f-4977-8a69-83aae7831b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'orders-grid_next']</value>
      <webElementGuid>4ad7862d-b7b8-45d3-8f2a-3c0ea97ca26b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
