<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Start date_k-icon k-i-calendar</name>
   <tag></tag>
   <elementGuidId>3821195a-7628-4f4b-8d87-473875c535e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-icon.k-i-calendar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b0a89501-6dde-4299-b812-44644b0005b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-calendar</value>
      <webElementGuid>a1c98623-e54e-44be-8bb8-dcd9053774d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit117&quot;]/body[@class=&quot;sidebar-mini layout-fixed control-sidebar-slide-open&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/form[1]/section[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;form-horizontal&quot;]/div[@class=&quot;cards-group&quot;]/div[@class=&quot;card card-default card-search&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;search-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-8&quot;]/span[@class=&quot;k-widget k-datepicker&quot;]/span[@class=&quot;k-picker-wrap k-state-default k-state-hover&quot;]/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-calendar&quot;]</value>
      <webElementGuid>b632ea56-b99c-4609-9a5b-6e3ff40d6e5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>e3076957-93cf-4d88-bbad-6d9bbdd2078b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
