<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_nopCommerce version 4.60.0_k-icon k-i-_1df4aa</name>
   <tag></tag>
   <elementGuidId>fffc004c-52d0-4064-8374-cc4cba88bc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='deae9a5e-1258-46cf-bdcd-ad326ee062ef']/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-icon.k-i-arrow-60-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2bbbd4c7-6479-41bb-9032-1d62e1677240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-60-left</value>
      <webElementGuid>20b2c9e8-40d9-4ac5-894a-3797732afed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deae9a5e-1258-46cf-bdcd-ad326ee062ef&quot;)/div[@class=&quot;k-header&quot;]/a[@class=&quot;k-link k-nav-prev k-state-hover&quot;]/span[@class=&quot;k-icon k-i-arrow-60-left&quot;]</value>
      <webElementGuid>0fa6260a-b0f0-4aa2-8614-6197a5e27f45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deae9a5e-1258-46cf-bdcd-ad326ee062ef']/div/a/span</value>
      <webElementGuid>6f2250db-2465-4020-8a2a-1fe5523aa104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>e9c5cfb5-1c19-4bb2-badd-f2d98718d993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
