<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_12</name>
   <tag></tag>
   <elementGuidId>fd073ffd-1c7b-4344-99d3-363f0d9c3e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dfba9f04-7a86-4bb0-b4c2-51a2eec284eb_cell_selected']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dfba9f04-7a86-4bb0-b4c2-51a2eec284eb_cell_selected > a.k-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e1ecd67-8c05-451f-92ff-8f29338315ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5ea11d1b-d7e3-485f-808c-185adde89a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>cd4de4a8-e8b6-4241-ad66-0a9c35285872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3744bfc1-a1e8-40cc-923a-510060fcb5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2023/9/12</value>
      <webElementGuid>502d8fc0-b8ae-423d-9e1e-7742fe4f145f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thursday, October 12, 2023</value>
      <webElementGuid>391aa7c8-03f0-4772-9017-3d640d05ecb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>da5b09f2-beb9-4c9a-8278-9125e67f61b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dfba9f04-7a86-4bb0-b4c2-51a2eec284eb_cell_selected&quot;)/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>5d86d2db-ec5d-4e69-a6e3-4793b5db668d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dfba9f04-7a86-4bb0-b4c2-51a2eec284eb_cell_selected']/a</value>
      <webElementGuid>dec60111-5e53-47e4-b4ec-42d734dd0bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'12')])[3]</value>
      <webElementGuid>492fc345-ccda-4808-89f9-a3ad404bb563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::a[12]</value>
      <webElementGuid>0811a8ef-1648-4f80-bebb-8f5d8c47810b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[2]/following::a[12]</value>
      <webElementGuid>8d5519c9-2b74-4b1e-84de-cb928f8ce888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[82]</value>
      <webElementGuid>8c2d9ad2-14bc-4be4-a852-e496db23aa24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/table/tbody/tr[2]/td[5]/a</value>
      <webElementGuid>37d07fce-2eac-4347-a892-4abcdccb7809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Thursday, October 12, 2023' and (text() = '12' or . = '12')]</value>
      <webElementGuid>1f0e4373-93c7-44e8-a380-fedf004231f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
