<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>50e59f5c-9280-4005-aa7d-590817183d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='00c55a1c-1749-4a0e-8d9f-d22105ffa66a']/div[2]/table/tbody/tr[2]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.k-weekend.k-state-hover > a.k-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f7f6ce7-dd5e-46b8-b3fc-0d91235aae02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>33ea698c-6300-4c3e-9bf3-0791113a8fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>49c1bda5-8e7b-45c6-a397-39602bd529b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2533dd31-9002-4c37-b21d-0d866afeba7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2023/6/2</value>
      <webElementGuid>01daea77-8ff8-4ea7-a9f3-ff52c83f763e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sunday, July 2, 2023</value>
      <webElementGuid>2dbc7094-aa91-4897-98c0-d583a07547af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>088a9d7b-b99a-4306-8e43-ff36b6c1da50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;00c55a1c-1749-4a0e-8d9f-d22105ffa66a&quot;)/div[@class=&quot;k-calendar-view&quot;]/table[@class=&quot;k-content k-month&quot;]/tbody[1]/tr[2]/td[@class=&quot;k-weekend k-state-hover&quot;]/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>06f6c9a5-7002-4cbe-8192-5b52de785b06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='00c55a1c-1749-4a0e-8d9f-d22105ffa66a']/div[2]/table/tbody/tr[2]/td/a</value>
      <webElementGuid>720297f4-2fa0-4263-bb60-f4e507c8b4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[7]</value>
      <webElementGuid>bb929276-b9b4-45f0-ae2d-5ba74312afe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[8]</value>
      <webElementGuid>5b1d15a9-c6a0-4737-960e-065e0c3677e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::a[8]</value>
      <webElementGuid>2b671f11-e3aa-4e04-9f0d-e3c0c6d6bf2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[32]</value>
      <webElementGuid>e494fe5c-5532-4a7f-a945-d6d1e038e781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/table/tbody/tr[2]/td/a</value>
      <webElementGuid>91622afd-0011-4baf-a28e-509d1a7bc163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Sunday, July 2, 2023' and (text() = '2' or . = '2')]</value>
      <webElementGuid>6da93969-fd17-4a7d-92c9-c5d17aa35227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
