<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Edit_customerroles-grid_next</name>
   <tag></tag>
   <elementGuidId>60cb19b6-10d7-4010-bbc9-a741e082f7ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customerroles-grid_next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='customerroles-grid_next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b6a84bef-7a8b-4285-81b4-74000866382a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item next disabled</value>
      <webElementGuid>c1034562-e254-448d-804c-12e4f0d75a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerroles-grid_next</value>
      <webElementGuid>073d9a8d-bc82-43c0-a818-4cd275ccd98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerroles-grid_next&quot;)</value>
      <webElementGuid>4d3d6b1d-02f0-4fe8-bfb0-ced369bfa31d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='customerroles-grid_next']</value>
      <webElementGuid>48612703-85ce-422f-a7f4-735ad9ccfb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customerroles-grid_paginate']/ul/li[3]</value>
      <webElementGuid>e6ecbb05-5ecf-4874-9d97-7de7e8cad930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[8]/following::li[3]</value>
      <webElementGuid>a55a5f89-a9d9-45dd-947a-a1e165792754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendors'])[2]/following::li[3]</value>
      <webElementGuid>c8209fa8-81fd-40da-8d7a-844f579fb7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[3]</value>
      <webElementGuid>e002a14a-1e98-4302-8d50-5b9da4280780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'customerroles-grid_next']</value>
      <webElementGuid>c89a3bc9-40e4-4a2e-bdc1-8c2886d584c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
