<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Biryani</name>
   <tag></tag>
   <elementGuidId>5749b152-1295-4346-8203-14ff5c468499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/button/div[2]/div/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>8ec61403-69bf-4cb3-9976-098277852139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Biryani</value>
      <webElementGuid>95a463a8-6756-4c75-9316-862ff1e1867a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/div[@class=&quot;nDVxx&quot;]/div[@class=&quot;_2NSqs&quot;]/div[@class=&quot;_3X3Bt&quot;]/div[@class=&quot;_1VxLu&quot;]/button[@class=&quot;_37IIF _1rZ-i&quot;]/div[@class=&quot;_23LIV&quot;]/div[@class=&quot;RNzoC&quot;]/b[1]</value>
      <webElementGuid>887815a4-0fd3-4023-a8ed-ae02fe0cc411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/button/div[2]/div/b</value>
      <webElementGuid>b3ad9d0c-8199-4fdb-82b2-a01daebcb24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::b[1]</value>
      <webElementGuid>642c175d-0358-459b-a196-aecaeb700c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[1]/following::b[1]</value>
      <webElementGuid>1972d1f7-dceb-4942-8a88-c84a82d8d920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dish'])[1]/preceding::b[1]</value>
      <webElementGuid>39929e0c-5ac7-4227-8aa0-03890990327e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Biryani']/parent::*</value>
      <webElementGuid>4e9ab4b5-3f23-47ef-9ffe-14a519a21f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>c5df0c54-d238-4e93-b76d-36bed9b3bb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Biryani' or . = 'Biryani')]</value>
      <webElementGuid>5f2704db-f097-43dc-b060-b9395aad4cc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
