<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Speakers</name>
   <tag></tag>
   <elementGuidId>0e717129-a348-4b4a-b564-34d94bc6dd29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sobe_d_b_6_1']/a/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sobe_d_b_6_1 > a.sl-sobe-carousel-sub-card-link > div.sl-sobe-carousel-sub-card-footer > span.sl-sobe-carousel-sub-card-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5598ea83-b536-4478-a928-4334963cf028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sl-sobe-carousel-sub-card-title</value>
      <webElementGuid>4eb81581-cdfb-4890-930c-d0181e2b60c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Speakers</value>
      <webElementGuid>fd24bcb9-d1dd-4d41-969b-57e97c62382e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sobe_d_b_6_1&quot;)/a[@class=&quot;sl-sobe-carousel-sub-card-link&quot;]/div[@class=&quot;sl-sobe-carousel-sub-card-footer&quot;]/span[@class=&quot;sl-sobe-carousel-sub-card-title&quot;]</value>
      <webElementGuid>7d2f5c98-a7e1-4257-a3a5-74570e079ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sobe_d_b_6_1']/a/div[2]/span</value>
      <webElementGuid>0f1233f2-3d42-4449-b8be-08128eb6a3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memory Cards'])[1]/following::span[1]</value>
      <webElementGuid>cb47a8cb-51b5-4340-8440-6864bc19072e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office Products'])[2]/following::span[2]</value>
      <webElementGuid>a08c7e32-4f90-461e-be7d-0c4751951c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Camera Accessories'])[1]/preceding::span[1]</value>
      <webElementGuid>1b5c22c4-63b3-43ff-b338-7998d8f3a05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Musical Instruments'])[3]/preceding::span[2]</value>
      <webElementGuid>56f3f95a-392d-4b30-a767-341e647a1b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Speakers']/parent::*</value>
      <webElementGuid>2a83c9b1-891b-419a-8eac-eb309860cbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/section/div/div/div/div/div/ol/li/a/div[2]/span</value>
      <webElementGuid>ec6d8ae3-6a3b-403b-b974-be9070bb575f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Speakers' or . = 'Speakers')]</value>
      <webElementGuid>01a4de4e-3084-4d2c-a26d-a0591a73df2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
