<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Minimum 6 characters required_showPass resman-icon resman-icon-eye-closed resman-pos-right</name>
   <tag></tag>
   <elementGuidId>8c268fb0-f4db-4e01-bd9d-fcdf33da3848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.showPass.resman-icon.resman-icon-eye-closed.resman-pos-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/form/div[2]/div[2]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b17bb856-440b-4c30-b215-f3524cf4fa11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>showPass resman-icon resman-icon-eye-closed resman-pos-right</value>
      <webElementGuid>2f59d1c7-efac-41a4-afb7-1d6d34f244c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;right-container&quot;]/div[@class=&quot;right-pane&quot;]/div[@class=&quot;registerWrapper&quot;]/div[@class=&quot;formWrapper&quot;]/form[@class=&quot;formTag&quot;]/div[@class=&quot;formElems&quot;]/div[@class=&quot;formField&quot;]/button[@class=&quot;eye-button resman-btn-empty resman-btn-small&quot;]/i[@class=&quot;showPass resman-icon resman-icon-eye-closed resman-pos-right&quot;]</value>
      <webElementGuid>1a8bb769-f203-4efa-a31a-e3b2c0818a57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/form/div[2]/div[2]/button/i</value>
      <webElementGuid>02153a27-a428-4fad-8959-bbf14593c54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>8582d105-6868-42ca-8ae0-b2312e95bd64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
