<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1Cart</name>
   <tag></tag>
   <elementGuidId>2434fabe-bb1f-4f2c-9a98-e2fec31468e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div/ul/li/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a._1T-E4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>453ae594-7677-4a70-95e1-3449e6debb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1T-E4</value>
      <webElementGuid>bf94f2e2-78d8-4812-9b96-0671d8e32ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/checkout</value>
      <webElementGuid>a0667c93-a074-4059-944b-2917b5b49d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Cart</value>
      <webElementGuid>967f2be3-913d-47fe-804b-bc04f2c89810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/header[@class=&quot;_76q0O&quot;]/div[@class=&quot;global-nav&quot;]/div[@class=&quot;_1EuBh&quot;]/ul[@class=&quot;_1JNGZ&quot;]/li[@class=&quot;_1fo6c&quot;]/div[@class=&quot;_1fmVk _30y3a&quot;]/div[1]/div[@class=&quot;_2CgXb&quot;]/a[@class=&quot;_1T-E4&quot;]</value>
      <webElementGuid>3d281fbe-972b-4334-8719-cb30ca41a5cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div/ul/li/div/div/div/a</value>
      <webElementGuid>265664e7-0a3b-4b38-975b-9438c45338e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mangaladevi Temple Rd, Pandeshwar, Mangaluru, Karnataka 575001, India'])[1]/following::a[1]</value>
      <webElementGuid>695bfb26-6578-42ff-b230-a16d3c907582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pandeshwar'])[1]/following::a[1]</value>
      <webElementGuid>2b78c57e-966d-4eef-afed-67a242b314e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attavar'])[1]/preceding::a[1]</value>
      <webElementGuid>eb49e3fd-690e-4fd0-bd89-b2e9d3564513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/checkout')]</value>
      <webElementGuid>62349723-215c-4933-86ef-bfc6a05e49d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>e1f99b4a-0742-40d1-b547-dd4847e90678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/checkout' and (text() = '1Cart' or . = '1Cart')]</value>
      <webElementGuid>8d2f8d93-d9c0-4d46-bd13-88ff5d2050bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
