<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONTINUE</name>
   <tag></tag>
   <elementGuidId>56bac738-4869-476a-937d-e9caea64fa6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='overlay-sidebar-root']/div/div/div[2]/div/div/div/form/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-ayg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fea55567-35c1-4567-afb9-097358a67406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-ayg</value>
      <webElementGuid>42e15399-1479-4bf4-b2fe-e1babcc9368c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUE</value>
      <webElementGuid>cdd65497-c543-4c7f-997d-b1336bbd0472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overlay-sidebar-root&quot;)/div[1]/div[1]/div[@class=&quot;_3vi_e&quot;]/div[@class=&quot;_12S7_&quot;]/div[1]/div[1]/form[1]/div[@class=&quot;_25qBi _2-hTu&quot;]/a[@class=&quot;a-ayg&quot;]</value>
      <webElementGuid>017ea461-b473-472b-b3c4-d0405b483f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overlay-sidebar-root']/div/div/div[2]/div/div/div/form/div[2]/a</value>
      <webElementGuid>4f7eac8e-178c-48bc-a150-83b716d5662e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CONTINUE')]</value>
      <webElementGuid>3fd2946f-6337-4349-8e9d-1ec09ee4644f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have a referral code?'])[1]/following::a[1]</value>
      <webElementGuid>e0313caf-d5a6-4e39-8c1c-3cb794941ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::a[1]</value>
      <webElementGuid>0b53e415-8247-466e-8d97-b416d7406c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[2]/preceding::a[1]</value>
      <webElementGuid>74a6ee5e-aa18-42d2-bdf8-f461ba7260f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTINUE']/parent::*</value>
      <webElementGuid>df1fae73-bd90-4710-a151-0becddd1c154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>4c550f14-4de1-4d6c-809e-e2ca1cef2024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'CONTINUE' or . = 'CONTINUE')]</value>
      <webElementGuid>aeea4470-817e-4036-aa7f-c43d957f6ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
