<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OffersNEW</name>
   <tag></tag>
   <elementGuidId>364c5d94-4c2a-4b0f-a90e-2d8a51f26423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div/ul/li[4]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>150cb5fb-aa8b-407e-9468-1d2975452d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1T-E4</value>
      <webElementGuid>e95700e7-7ff3-4690-b599-6f6c673b5637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/offers-near-me</value>
      <webElementGuid>9cb4d88d-3529-461a-8a44-1f95b0017adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OffersNEW</value>
      <webElementGuid>9740a7a3-b50a-445d-8a15-e2c010560839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/header[@class=&quot;_76q0O&quot;]/div[@class=&quot;global-nav&quot;]/div[@class=&quot;_1EuBh&quot;]/ul[@class=&quot;_1JNGZ&quot;]/li[@class=&quot;_1fo6c&quot;]/div[@class=&quot;_2CgXb&quot;]/a[@class=&quot;_1T-E4&quot;]</value>
      <webElementGuid>510c0eaa-0dea-4acb-b469-a2da0f4f45a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div/ul/li[4]/div/a</value>
      <webElementGuid>a7036139-9673-4cd3-91e0-270ba21bd2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::a[1]</value>
      <webElementGuid>027be620-933a-403b-a5aa-05c5e1beedc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::a[2]</value>
      <webElementGuid>8c66efcc-ec56-4c1b-80e8-b8bc4761fd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>51fd3f86-fcab-4b33-b029-c8108a40a175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Offers']/parent::*</value>
      <webElementGuid>650f7a1d-8e40-47ef-8095-b39934988c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/offers-near-me')]</value>
      <webElementGuid>2468e019-6abc-4797-8c38-601e46330ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a</value>
      <webElementGuid>25f87b8f-5cf6-465a-a97a-a68d660a5aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/offers-near-me' and (text() = 'OffersNEW' or . = 'OffersNEW')]</value>
      <webElementGuid>a941fd16-ba62-4b83-a621-ac9cda3db182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
