<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search</name>
   <tag></tag>
   <elementGuidId>8119e331-e03c-46a5-a285-85b19778ab4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div/ul/li[5]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6643c76-e319-41ce-b705-4bed176b303d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1T-E4</value>
      <webElementGuid>ac04aafd-106b-4d19-8744-a2401340430d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search</value>
      <webElementGuid>b8e15e9e-1be9-4fe0-9757-d456b836dc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b2b944e6-d6af-4a9a-b63a-a7885170746d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/header[@class=&quot;_76q0O&quot;]/div[@class=&quot;global-nav&quot;]/div[@class=&quot;_1EuBh&quot;]/ul[@class=&quot;_1JNGZ&quot;]/li[@class=&quot;_1fo6c&quot;]/div[@class=&quot;_2CgXb&quot;]/a[@class=&quot;_1T-E4&quot;]</value>
      <webElementGuid>df2a15a7-4e9b-45f2-b327-fa2d74c6ede7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div/ul/li[5]/div/a</value>
      <webElementGuid>0a10c353-8bfe-4d77-ae94-0cf685b4726e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[1]/following::a[1]</value>
      <webElementGuid>1ea94346-9aef-4821-86ff-77ac6b39dc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best offers for you'])[1]/preceding::a[1]</value>
      <webElementGuid>7d7a387f-d613-43e6-b859-7f8362f0fe9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search')]</value>
      <webElementGuid>ad0a7200-1d47-44b1-bc9e-56d9cbf3b3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a</value>
      <webElementGuid>93308461-4a05-4118-884c-bef3ef702078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>dadf2e7c-3460-48ea-aea3-856f20f7f569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
