<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CakeDish</name>
   <tag></tag>
   <elementGuidId>aad8107c-7958-4f56-b91f-90e3edaded40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button._37IIF._1rZ-i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0cc23c0-5d55-4747-8a2d-8b97d85a648a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_37IIF _1rZ-i</value>
      <webElementGuid>5706d852-6339-40c0-a788-99126c0ee012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>autosuggest-item</value>
      <webElementGuid>9995ed01-ce6a-4464-a29d-fc8a65efef8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CakeDish</value>
      <webElementGuid>e2cc6537-579b-4ce9-83e3-8ffdb88acca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/div[@class=&quot;nDVxx&quot;]/div[@class=&quot;_2NSqs&quot;]/div[@class=&quot;_3X3Bt&quot;]/div[@class=&quot;_1VxLu&quot;]/button[@class=&quot;_37IIF _1rZ-i&quot;]</value>
      <webElementGuid>4c405588-e77d-424b-a8f0-da4c56667937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/button</value>
      <webElementGuid>cc0c660d-f497-47c5-b3c0-79de8c08e58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[2]</value>
      <webElementGuid>27e74f4f-dc8b-47c3-9e03-9422d455905b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW'])[1]/following::button[2]</value>
      <webElementGuid>3d09e581-48e3-4a6a-912c-b6f7dec67402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>a74994e3-4e52-4035-88f7-c6906c9544a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CakeDish' or . = 'CakeDish')]</value>
      <webElementGuid>800a766e-5e00-4196-8da9-5d768a19c7b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
