<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mobile number already exists</name>
   <tag></tag>
   <elementGuidId>16efa044-07a3-4f7a-9e00-abaafcebca0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._3--N8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b2a228c-9eda-463e-a555-e77970564323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3--N8</value>
      <webElementGuid>c97a2575-3b8a-48ab-a0a9-ff752cd0f304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile number already exists</value>
      <webElementGuid>ca022118-85b6-45cc-bc34-355efc2de6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_2b6Ch _3US4F&quot;]/div[@class=&quot;_3WqGq&quot;]/div[@class=&quot;_1vd_H&quot;]/div[@class=&quot;_2VSxh&quot;]/div[@class=&quot;_3--N8&quot;]</value>
      <webElementGuid>317d1a9e-5e99-44e9-a184-89edd95c527a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div</value>
      <webElementGuid>ab26bdd7-0e3d-439c-8fe6-324f198ced59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roha'])[1]/following::div[10]</value>
      <webElementGuid>7d7515be-5e94-4bf7-b263-e42844549736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangipur'])[1]/following::div[11]</value>
      <webElementGuid>2a19958a-0f9c-451c-ae9c-38201a227b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::div[6]</value>
      <webElementGuid>c2032790-d344-4878-9df7-a836bcbcd0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobile number already exists']/parent::*</value>
      <webElementGuid>35df7749-d86c-424f-9e65-ba5d42a6de93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>b5d624fe-d643-45fa-b430-5425de327914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Mobile number already exists' or . = 'Mobile number already exists')]</value>
      <webElementGuid>57713c7b-7ce7-41d8-9a5e-961c9f076965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
