<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ADD</name>
   <tag></tag>
   <elementGuidId>c05b562f-2c64-4c44-adfb-e84daa2ac978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[5]/div/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._1RPOp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3505b409-c6fa-4eac-a6cd-b7cc1ff097f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1RPOp</value>
      <webElementGuid>572dfe1e-76eb-4915-bc79-d28b2ad6e621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD</value>
      <webElementGuid>add11d86-5833-4e77-8160-b651179cb4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/div[@class=&quot;nDVxx&quot;]/div[1]/div[@class=&quot;OF_5P&quot;]/div[2]/div[@class=&quot;MenuCarousel_container__2hf2_&quot;]/div[@class=&quot;Carousel_slider__RcmSv MenuCarousel_carousel__1ttjg&quot;]/div[@class=&quot;Carousel_slide__klR8u MenuCarousel_slide__WXsCo&quot;]/div[@class=&quot;Card_container__2-UC7&quot;]/div[@class=&quot;Card_meta__2imYX&quot;]/div[@class=&quot;Card_metaFooter__3ZCVb&quot;]/div[@class=&quot;Card_addButton__3QUZ5&quot;]/div[@class=&quot;_3L1X9 _211P0 Card_addButtonButton__3zbQ6&quot;]/div[@class=&quot;_1RPOp&quot;]</value>
      <webElementGuid>41ab382c-5836-4d68-b143-b8c1f40e976f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[5]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>f48a5c2e-c7fd-48f2-8610-a9c56190e155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Picks'])[1]/following::div[8]</value>
      <webElementGuid>1aa2988f-4889-47a0-b11f-4b3f53719e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABOVE ₹500'])[1]/following::div[14]</value>
      <webElementGuid>40e713fc-9276-48ad-8b14-e26132cadb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::div[1]</value>
      <webElementGuid>43bade4d-ba62-42ed-a5b5-2fb9d4fcd28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD'])[2]/preceding::div[5]</value>
      <webElementGuid>63458fd6-e05f-43a9-8292-0d269d95f792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADD']/parent::*</value>
      <webElementGuid>a6f43497-c96e-4657-953f-d7adba198c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>4b5282da-c6b1-42d0-8782-332267c34a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ADD' or . = 'ADD')]</value>
      <webElementGuid>26f19e5b-6de9-4dba-8867-8b10aaf0046f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[4]/div/div/div[2]/div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>c857604e-e922-4ea1-8aac-c541171ad7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caramel White Chocochip Cake'])[1]/following::div[6]</value>
      <webElementGuid>f67a9ff1-5613-4260-b93c-2d4b2e80bb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By 7th Heaven'])[1]/following::div[16]</value>
      <webElementGuid>1e26c278-ff66-41e8-a933-9998d82a3522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::div[2]</value>
      <webElementGuid>f9dde792-95a2-4d36-8a66-de7d00e33a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>efaf17a4-9595-458f-ba1e-c22f649c9609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
