<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Popular Cuisines_styles_img__3HNZ4</name>
   <tag></tag>
   <elementGuidId>ce2e91e8-9960-45cd-932c-a7a773be6d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div/div[3]/div/div/div/div/div/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.styles_img__3HNZ4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e5657855-f257-494f-ac9c-917fe7b65107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_img__3HNZ4</value>
      <webElementGuid>4a6667cc-c6e8-4726-a9ac-f0dd033caebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>90171d91-2a8f-4ef4-82af-6490949a905c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/b4ff78ecc5b8b66f732dd06228916d65</value>
      <webElementGuid>d7f22527-dd7a-49a5-a15f-22f88732d089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/div[@class=&quot;nDVxx&quot;]/div[@class=&quot;_2NSqs&quot;]/div[@class=&quot;_3X3Bt&quot;]/div[@class=&quot;Search_wrapper__lQvnw _1cEc4&quot;]/div[@class=&quot;Search_widgetsV2__27BBR&quot;]/div[@class=&quot;styles_container__jxIGl&quot;]/div[3]/div[@class=&quot;styles_slider__podEu&quot;]/div[@class=&quot;styles_row__1ivP1&quot;]/div[@class=&quot;styles_slide__2c207&quot;]/div[@class=&quot;Carousel_slide__klR8u&quot;]/div[1]/div[@class=&quot;styles_container__1Nshr&quot;]/button[@class=&quot;Ripple_container__17nxL styles_containerImg__3AXGh&quot;]/img[@class=&quot;styles_img__3HNZ4&quot;]</value>
      <webElementGuid>f3bef5a0-907b-48cb-aea1-6edb8f1969f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div/div[3]/div/div/div/div/div/div/button/img</value>
      <webElementGuid>ca3623a4-e9ce-407c-97d5-c3279c209b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/b4ff78ecc5b8b66f732dd06228916d65')]</value>
      <webElementGuid>6e232c1c-162c-41bf-90e6-d2779054c569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e0610cfd-cb90-4722-98e6-eede47cafea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/b4ff78ecc5b8b66f732dd06228916d65']</value>
      <webElementGuid>df6bac0b-90f4-494b-8aa1-dcec69d5fa27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[2]/div/div/div/button/img</value>
      <webElementGuid>b08c39fa-4ff1-4330-845c-99c89def8c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/5dd234f7decdac4b4f71a2ff1408e10f')]</value>
      <webElementGuid>9e990f68-0bd2-4965-9ec4-57be125ffebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/img</value>
      <webElementGuid>c7bfe717-2685-4e2c-9984-238234e58ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/5dd234f7decdac4b4f71a2ff1408e10f']</value>
      <webElementGuid>5a5b856e-3f09-4ec1-88c6-cd79fc412d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[7]/div/div/div/button/img</value>
      <webElementGuid>cdb5b399-666b-48ed-b0a3-b2c8a0a52a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/8322f6d6df488dc1f5a6674cfe863f0f')]</value>
      <webElementGuid>55e122ee-0434-46a7-b9d0-1aa21712fe62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/button/img</value>
      <webElementGuid>2d9cb8c9-4635-4d0a-9f85-9b39367b20e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/8322f6d6df488dc1f5a6674cfe863f0f']</value>
      <webElementGuid>898a08bb-325f-4c1e-97ff-096db3aaf7af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
