<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Popular Cuisines_styles_img__3HNZ4_1</name>
   <tag></tag>
   <elementGuidId>4fd17c64-939c-4aed-b1f1-dfe9eef24224</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[4]/div/div/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d9ef7cbb-7302-42b8-81e5-e9fef39a2150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_img__3HNZ4</value>
      <webElementGuid>7d9d679d-5ad7-4684-bd26-9ce9f9ca1bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>be07178d-7996-40d7-b9cf-9b6ecc39ca7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/87664acb0f9dd95d10a549bb8190ab27</value>
      <webElementGuid>197696e3-e9d8-4685-8cea-e6e083de4b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/div[@class=&quot;nDVxx&quot;]/div[@class=&quot;_2NSqs&quot;]/div[@class=&quot;_3X3Bt&quot;]/div[@class=&quot;Search_wrapper__lQvnw _1cEc4&quot;]/div[@class=&quot;Search_widgetsV2__27BBR&quot;]/div[@class=&quot;styles_container__jxIGl&quot;]/div[3]/div[@class=&quot;styles_slider__podEu&quot;]/div[@class=&quot;styles_row__1ivP1&quot;]/div[@class=&quot;styles_slide__2c207&quot;]/div[@class=&quot;Carousel_slide__klR8u&quot;]/div[1]/div[@class=&quot;styles_container__1Nshr&quot;]/button[@class=&quot;Ripple_container__17nxL styles_containerImg__3AXGh&quot;]/img[@class=&quot;styles_img__3HNZ4&quot;]</value>
      <webElementGuid>e005ce6c-fb52-49a3-bcbf-4926942129e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[3]/div/div[3]/div/div/div[4]/div/div/div/button/img</value>
      <webElementGuid>72f257d9-0938-40fe-9904-1e19868d8dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/87664acb0f9dd95d10a549bb8190ab27')]</value>
      <webElementGuid>2dd626c4-c71e-4897-b9c0-48b49f73b53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button/img</value>
      <webElementGuid>c7b1ee69-0c2a-4135-80dd-5a3a48bdb48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/rng/md/carousel/production/87664acb0f9dd95d10a549bb8190ab27']</value>
      <webElementGuid>cafcc0fb-68c5-4f8c-ac3a-85359f29af5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
