<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_FAQs</name>
   <tag></tag>
   <elementGuidId>d33450fa-0202-479f-a327-4b4a8dfce437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[3]/div[2]/div/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e37dada2-2fa4-49f8-82e3-a7d90a1a1832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2y6HV</value>
      <webElementGuid>0749f9d0-57d7-4072-85d4-02968fdcd5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FAQs</value>
      <webElementGuid>554470dc-6e6e-4a55-8bf1-ce5b566872a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_3arMG&quot;]/div[@class=&quot;nDVxx&quot;]/div[@class=&quot;_1w2w1&quot;]/div[@class=&quot;_3tDvm&quot;]/div[@class=&quot;_2QhOV _3glSS&quot;]/div[@class=&quot;_3R9IF&quot;]/div[@class=&quot;_2gu8R&quot;]/ul[1]/li[@class=&quot;_2y6HV&quot;]</value>
      <webElementGuid>dda21a57-3391-4f5b-9ed9-f9aad6e59931</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/div[2]/div/div/ul/li[3]</value>
      <webElementGuid>12c77658-2401-412a-a9e5-e55856504e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal'])[1]/following::li[1]</value>
      <webElementGuid>dfbcd60f-7614-46a1-a6e8-7a2e74d8c974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner Onboarding'])[1]/following::li[2]</value>
      <webElementGuid>d6412a1a-1e5c-4c8f-92f5-59179446f756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[3]</value>
      <webElementGuid>a95510d5-dbed-466e-af0b-c4b4ccf7666a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'FAQs' or . = 'FAQs')]</value>
      <webElementGuid>26e7f225-3ab6-4dd7-b817-19db8ec7ed17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
