<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>e015e62c-9d11-4dc2-b3ee-dfeb909eba1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register_Layer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='register_Layer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7df8201-2986-4e26-a2b7-f7cb9e75377e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Jobseeker Register</value>
      <webElementGuid>ccf638a6-24c6-44cb-84d6-74dce597e85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.naukri.com/registration/createAccount?othersrcp=22636</value>
      <webElementGuid>d6daca0d-a7df-469b-9513-f25bb45f2db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register_Layer</value>
      <webElementGuid>3eaa4714-922e-4824-8238-c2e23f50312d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-track</name>
      <type>Main</type>
      <value>Main Navigation Register|Register Icon</value>
      <webElementGuid>9129ec56-2893-479d-8ba7-3b17803c4bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nI-gNb-lg-rg__register</value>
      <webElementGuid>ddb2c5af-5753-4572-932a-79bf3a6c1f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>ecdf0e99-69bc-4168-9e2f-e58cddb959b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_Layer&quot;)</value>
      <webElementGuid>0b5e4561-69e8-4900-9136-841140f414d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='register_Layer']</value>
      <webElementGuid>81a44acf-095a-487a-86bc-903e8e9f6994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div[2]/div/a[2]</value>
      <webElementGuid>ef6d4162-be25-4c30-af0b-a096a5fd5fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>85014fdb-ff79-46de-bfad-58dbbcbebd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>be63b4ae-0667-41a1-a36f-e9e19d6110f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job letter samples'])[1]/following::a[2]</value>
      <webElementGuid>d51864d4-464b-43d8-a2f8-0f920dc51d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For employers'])[1]/preceding::a[1]</value>
      <webElementGuid>47d88dae-f431-46f4-9509-64afea7d3dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post a job'])[1]/preceding::a[2]</value>
      <webElementGuid>4d7a5ebf-fe48-4f6a-8430-9543d100f7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>3a9b5c78-260f-4a21-bf67-b95b09c2b4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.naukri.com/registration/createAccount?othersrcp=22636')]</value>
      <webElementGuid>755cc897-7fca-4ad0-acf4-47e98e0fe6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>1321f20e-079f-4e03-8bf3-ba5a7bccf529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Jobseeker Register' and @href = 'https://www.naukri.com/registration/createAccount?othersrcp=22636' and @id = 'register_Layer' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>1ec3eacc-1320-4d28-b659-2e27f53518f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
