<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>b3a0267e-1b2d-4d4c-aebf-0aa91032072d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceIImhAmJ3juFTeskclZUd4Q']/div/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.action-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a630ddfa-077e-413d-b803-58be2dff3200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action-inner</value>
      <webElementGuid>9d525227-309e-4dec-b1d7-539bac352760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50px</value>
      <webElementGuid>6d5dfc8b-9162-463f-84af-59b38d7f9e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ಸೈನ್ ಇನ್</value>
      <webElementGuid>934b333f-bbc6-46aa-a2be-96b47786ef9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceIImhAmJ3juFTeskclZUd4Q&quot;)/div[@class=&quot;rhf-state-signin&quot;]/div[@class=&quot;rhf-sign-in-button&quot;]/a[@class=&quot;action-button&quot;]/span[@class=&quot;action-inner&quot;]</value>
      <webElementGuid>7dcaa597-784f-4375-8f05-c719cddc67ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceIImhAmJ3juFTeskclZUd4Q']/div/div/a/span</value>
      <webElementGuid>a40e813c-7ddc-462f-aaac-5635d75eb80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ವೈಯಕ್ತೀಕರಿಸಿದ ಶಿಫಾರಸುಗಳನ್ನು ನೋಡಿ'])[1]/following::span[1]</value>
      <webElementGuid>94a7308c-3711-4e20-a894-5c39d7c01ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ಎಲ್ಲಾ ಡಿಲ್ಸ್‌ಗಳನ್ನು ನೋಡಿ'])[1]/following::span[19]</value>
      <webElementGuid>ace235a7-966d-4ba3-a1ae-a1dc60b2a8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ಇಲ್ಲಿಂದ ಆರಂಭ ಮಾಡಿ.'])[2]/preceding::span[1]</value>
      <webElementGuid>c5ce4d60-1a8d-4067-8703-45a011206106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div/a/span</value>
      <webElementGuid>1e33f5a8-9b9a-4778-afec-a9ff2689d82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ಸೈನ್ ಇನ್' or . = 'ಸೈನ್ ಇನ್')]</value>
      <webElementGuid>4c2cc1e3-1e43-40f9-889b-550d953d3dbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
